### ISSUE TITLE
deploy to matic

### ISSUE THREAD

**Issue by tobowers** [makerdao/multicall#16]
Hello! I'm interested in using multicall on matic (mainnet and mumbai). I don't see any deploy instructions or else I would just open a PR with the deployment.

**Comment by Elyx0** [comment]
Interested as well, it's about time. Did you go on with this @tobowers ?

**Comment by tobowers** [comment]
> Interested as well, it's about time. Did you go on with this @tobowers ?

I did!

https://github.com/quorumcontrol/kasumah/tree/main/packages/kasumah-multicall

https://github.com/quorumcontrol/kasumah/blob/main/packages/kasumah-multicall/deployments/137/Multicall.json

https://explorer-mainnet.maticvigil.com/address/0x11ce4B23bD875D7F5C6a31084f55fDe1e9A87507/contracts

**Comment by ethanbennett** [comment]
Just added polygon and mumbai to the readme, thanks @tobowers!

**Comment by Elyx0** [comment]
Do you think you can verify them @tobowers at https://polygonscan.com ?
