### ISSUE TITLE
Deduplicate

### ISSUE THREAD

**Issue by nmushegian** [makerdao/multicall#2]
I'm guessing only one of these two repos is getting formally verified

https://github.com/dapphub/ds-proxy/blob/master/src/proxy.sol

I might be misunderstanding the purpose here, since you're using staticcall

**Comment by gbalabasquer** [comment]
This project is just for reading purposes. It takes several static calls, execute them together and attaches the blocknumber retrieving all the information together. This is very helpful for UIs when trying to reach data from the chain.

**Comment by levity** [comment]
If only we’d kept my original whimsical name for this, “readalot”, this confusion might have been averted! :)

**Comment by tyler17** [comment]
I don't know, what if people confuse that with this very educational [Sir Readalot game](http://www.roomrecess.com/mobile/SirReadalot/play.html)
