### ISSUE TITLE
Is withSigner required when calling aggregate method?

### ISSUE THREAD

**Issue by SixBull** [makerdao/multicall#36]
When I call the “aggregate” function to query the balance of a token, it always prompts “sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.0)”.

Any one help? Thanks!

**Comment by SixBull** [comment]
Fine, fine, fine, I know how to solve my problem..

The “aggregate” function is compiled into a "nonpayable" type by default, which requires wallet signature operations. But if your dapp only uses it to do some view and pure query operations, you can change the "stateMutability" of "aggregate" to "view" in the abi of the multicall contract. then the problem solved...

**Comment by goodwasif** [comment]
Thanks @SixBull  <3
You saved my day
